blank_issues_enabled: true
contact_links:
  - name: Discussion
    url: https://github.com/itxtoledo/ethereum-rpc-pool/discussions
    about: Ask questions and discuss ideas here before opening an issue.
